# config/packages/security.yaml
security:
    # Hashage des mots de passe (Cybersécurité oblige !)
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Le fournisseur d'utilisateurs (basé sur ton entité Admin)
    providers:
        app_admin_provider:
            entity:
                class: App\Entity\Admin
                property: email # On se connecte avec l'email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_admin_provider
            
            # Configuration du formulaire de login
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true # Protection CSRF activée
                default_target_path: app_admin_dashboard # Redirection après succès

            logout:
                path: app_logout
                target: app_home # Redirection après déconnexion

    # Restrictions d'accès globales (Page 194 de ton cours)
    access_control:
        # Seuls les admins peuvent accéder au back-office
        - { path: ^/admin, roles: ROLE_ADMIN }